name: CD
on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
env:
    path_to_document: 'main.tex'
    path_to_pdf: 'main.pdf'
permissions:
  contents: write
jobs:
    create_latex_release:
      name: Create a release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
        - name: Build LaTeX document
          uses: xu-cheng/latex-action@3.2.0
          with:
            root_file: ${{env.path_to_document}}
            latexmk_use_xelatex: true
        - name: Download all artifacts
          uses: actions/download-artifact@v4.1.4
        - name: Get current date
          run: echo "CURRENT_DATETIME=$(date +'%d-%m-%YT%H%M%S')" >> $GITHUB_ENV
        - name: Create date tag
          uses: rickstaa/action-create-tag@v1.7.2
          with:
            tag: ${{env.CURRENT_DATETIME}}
        - name: Release
          uses: softprops/action-gh-release@v2.0.4
          with:
            files: ${{env.path_to_pdf}}
            tag_name: ${{env.CURRENT_DATETIME}} 
            draft: false
            prerelease: false
            make_latest: true