name: CD
on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
env:
    latex_source_dir: 'latex'
    path_to_document: 'main.tex'
    path_to_pdf: 'main.pdf'
    path_to_artifact_pdf: 'pdf/main.pdf'
    path_to_old_document: 'old-latex/main.tex'
    path_to_diff_document: 'changes.tex'
    path_to_diff_pdf: 'changes.pdf'
permissions:
  contents: write
jobs:
    checkout_base_document:
        if: startsWith(github.event.pull_request.head.ref, 'latex')
        name: Retrieve old document
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
              with:
                ref: ${{github.event.pull_request.base.sha}}
            - name: Copy old document
              run: cp -r latex old-latex
            - name: Upload old document
              uses: actions/upload-artifact@v4.3.1
              with:
                name: old-latex
                path: old-latex/

    build_latex:
        if: startsWith(github.event.pull_request.head.ref, 'latex')
        name: Build LaTeX Document
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: Build LaTeX document
              uses: xu-cheng/latex-action@3.2.0
              with:
                working_directory: ${{env.latex_source_dir}}
                root_file: ${{env.path_to_document}}
            - name: Upload PDF
              uses: actions/upload-artifact@v4.3.1
              with:
                name: pdf
                path: ${{env.latex_source_dir}}/${{env.path_to_pdf}}
    
    create_latex_release:
        name: Create a release with changes
        needs: [checkout_base_document, build_latex]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: Install latexdiff
              run: sudo apt-get install -y latexdiff
            - name: Download all artifacts
              uses: actions/download-artifact@v4.1.4
            - name: Create diff document
              run: latexdiff ${{env.path_to_old_document}} ${{env.latex_source_dir}}/${{env.path_to_document}} > ${{env.path_to_diff_document}}
            - name: Build diff document
              uses: xu-cheng/latex-action@3.2.0
              with:
                root_file: ${{env.path_to_diff_document}}
            - name: Get current date
              run: echo "CURRENT_DATETIME=$(date +'%d-%m-%YT%H%M%S')" >> $GITHUB_ENV
            - name: Create date tag
              uses: rickstaa/action-create-tag@v1.7.2
              with:
                tag: ${{env.CURRENT_DATETIME}}
            - name: Release
              uses: softprops/action-gh-release@v2.0.4
              with:
                files: |
                  ${{env.path_to_artifact_pdf}}
                  ${{env.path_to_diff_pdf}}
                tag_name: ${{env.CURRENT_DATETIME}} 
                draft: false
                prerelease: false
                make_latest: true